export * from './+collaborator';
export * from './+customer';
export * from './+dashboard';
export * from './+mission';
export * from './+role';
export * from './+setting';
export * from './+skill';
export * from './shared';
export * from './+home';
export { AppComponent } from './app.component';